/* Generated By:JavaCC: Do not edit this line. TCRL_ParserConstants.java */
//********************************************************************************
//							        PAQUETE
//********************************************************************************
// Este es el PAQUETE en FASTEST al cual perteneceran las CLASES generadas
// por javaCC para el REFINAMIENTO a JAVAS
package client.blogic.testing.refinementOld;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TCRL_ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PREAMBLE = 10;
  /** RegularExpression Id. */
  int EPILOGUE = 11;
  /** RegularExpression Id. */
  int ABSTRACTION = 12;
  /** RegularExpression Id. */
  int SYNONYM = 13;
  /** RegularExpression Id. */
  int PLTYPE = 14;
  /** RegularExpression Id. */
  int ENUMERATION = 15;
  /** RegularExpression Id. */
  int ARRAY = 16;
  /** RegularExpression Id. */
  int POINTER = 17;
  /** RegularExpression Id. */
  int STRUCTURE = 18;
  /** RegularExpression Id. */
  int LIST = 19;
  /** RegularExpression Id. */
  int SLL = 20;
  /** RegularExpression Id. */
  int DLL = 21;
  /** RegularExpression Id. */
  int CLL = 22;
  /** RegularExpression Id. */
  int DCLL = 23;
  /** RegularExpression Id. */
  int FILE = 24;
  /** RegularExpression Id. */
  int DB = 25;
  /** RegularExpression Id. */
  int LINEAR = 26;
  /** RegularExpression Id. */
  int RPL = 27;
  /** RegularExpression Id. */
  int FPL = 28;
  /** RegularExpression Id. */
  int RFR = 29;
  /** RegularExpression Id. */
  int ENDOFFILE = 30;
  /** RegularExpression Id. */
  int ENDOFLINE = 31;
  /** RegularExpression Id. */
  int CHAR = 32;
  /** RegularExpression Id. */
  int INT = 33;
  /** RegularExpression Id. */
  int VARCHAR = 34;
  /** RegularExpression Id. */
  int NUMBER = 35;
  /** RegularExpression Id. */
  int ID = 36;
  /** RegularExpression Id. */
  int COLON = 37;
  /** RegularExpression Id. */
  int ARROW = 38;
  /** RegularExpression Id. */
  int DEQUAL = 39;
  /** RegularExpression Id. */
  int LBRACKET = 40;
  /** RegularExpression Id. */
  int RBRACKET = 41;
  /** RegularExpression Id. */
  int LPAREN = 42;
  /** RegularExpression Id. */
  int RPAREN = 43;
  /** RegularExpression Id. */
  int COMMA = 44;
  /** RegularExpression Id. */
  int EOL = 45;
  /** RegularExpression Id. */
  int STRING = 46;
  /** RegularExpression Id. */
  int SPECID = 47;
  /** RegularExpression Id. */
  int IMPLID = 48;
  /** RegularExpression Id. */
  int RULES = 49;
  /** RegularExpression Id. */
  int PLCODE = 50;
  /** RegularExpression Id. */
  int CODE = 56;
  /** RegularExpression Id. */
  int dom = 57;
  /** RegularExpression Id. */
  int ran = 58;
  /** RegularExpression Id. */
  int cardinal = 59;
  /** RegularExpression Id. */
  int partition = 60;
  /** RegularExpression Id. */
  int AS = 61;
  /** RegularExpression Id. */
  int ID_ABSTRACTION = 62;
  /** RegularExpression Id. */
  int END_ABSTRACTION = 72;
  /** RegularExpression Id. */
  int SET = 73;
  /** RegularExpression Id. */
  int EOL_ABSTRACTION = 74;
  /** RegularExpression Id. */
  int PLCODE_ABSTRACTION = 75;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int CommentState = 1;
  /** Lexical state. */
  int LineCommentState = 2;
  /** Lexical state. */
  int PLCodeState = 3;
  /** Lexical state. */
  int Abstraction = 4;
  /** Lexical state. */
  int Abstraction_PLCode = 5;
  /** Lexical state. */
  int CommentStateAbstraction = 6;
  /** Lexical state. */
  int LineCommentStateAbstraction = 7;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "<token of kind 9>",
    "<PREAMBLE>",
    "<EPILOGUE>",
    "<ABSTRACTION>",
    "\"SYNONYM\"",
    "\"PLTYPE\"",
    "\"ENUMERATION\"",
    "\"ARRAY\"",
    "\"POINTER\"",
    "\"STRUCTURE\"",
    "\"LIST\"",
    "\"SLL\"",
    "\"DLL\"",
    "\"CLL\"",
    "\"DCLL\"",
    "\"FILE\"",
    "\"DB\"",
    "\"LINEAR\"",
    "\"RPL\"",
    "\"FPL\"",
    "\"RFR\"",
    "\"ENDOFFILE\"",
    "\"ENDOFLINE\"",
    "\"CHAR\"",
    "\"INT\"",
    "\"VARCHAR\"",
    "<NUMBER>",
    "<ID>",
    "\":\"",
    "\"==>\"",
    "\"==\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"\\n\"",
    "<STRING>",
    "<SPECID>",
    "<IMPLID>",
    "\"@RULES\"",
    "<PLCODE>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"/*\"",
    "\"//\"",
    "<CODE>",
    "\"dom\"",
    "\"ran\"",
    "\"#\"",
    "\"P\"",
    "\"AS\"",
    "<ID_ABSTRACTION>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 69>",
    "<token of kind 70>",
    "<token of kind 71>",
    "\"@ENDABSTRACTION\"",
    "\"@SET\"",
    "\"\\n\"",
    "<PLCODE_ABSTRACTION>",
    "\"-->\"",
  };

}
