package client.presentation.commands;


import java.io.*;
import client.presentation.ClientTextUI;
import client.blogic.management.ii.events.FastestResetted;
import client.blogic.management.ii.EventAdmin;



/**
 * An instance of this class allow the removal of all information loaded or generated by
 * Fastest, such as a Z specification, the selection of operations to be tested, tactics,
 * test trees, test cases, etc.
 * @author Pablo Rodriguez Monetti
 */
public class ResetCommand implements Command{ 

    /**
     * Runs this command.
     * @param clientTextUI
     * @param args
     */
    @Override
	public void run(ClientTextUI clientTextUI, String args){
		try{
            PrintWriter output = clientTextUI.getOutput();
            if (!args.equals("")){
        		output.println("Invalid parameters.  Try 'help'.");
    		}
    		else{
                EventAdmin eventAdmin = EventAdmin.getInstance();            
                eventAdmin.announceEvent(new FastestResetted());
            }

        }
        catch(Exception e){
            e.printStackTrace();            
        }
	}


} 
 
